export type {
  AutoCommitConfig,
  AutoCommitFrequencyInput,
  BrowserDatastoreConfig,
  BrowserStorageType,
  ByteSizeInput,
  CapacityConfig,
  CapacityPolicy,
  DatastoreConfig,
  DatastoreErrorEvent,
  DatastoreErrorListener,
  FileDatastoreConfig,
  FileTargetByDirectoryConfig,
  FileTargetByPathConfig,
  FileTargetConfig,
  IndexedDBConfig,
  InputTimeseriesRecord,
  LocalStorageConfig,
  MemoryDatastoreConfig,
  NativeAggregateExpression,
  NativeAggregateFunction,
  NativeComparisonOperator,
  NativeFilterExpression,
  NativeOrderBy,
  NativeQueryRequest,
  NativeQueryResultRow,
  NativeScalar,
  OpfsConfig,
  PersistedTimeseriesRecord,
  QueryEngineModule,
  QueryExecutionOptions,
  QueryLanguage,
  RecordId,
  RecordPayload,
  SupportedNestedValue,
  SupportedValue,
  TimeRangeQuery,
  TimeseriesRecord,
  TimestampInput,
} from './types.js';

export {
  BinaryFormatError,
  ClosedDatastoreError,
  ConfigurationError,
  DatabaseLockedError,
  IndexCorruptionError,
  InvalidQueryRangeError,
  PageCorruptionError,
  QueryEngineNotRegisteredError,
  QueryParseError,
  QueryValidationError,
  QuotaExceededError,
  StorageEngineError,
  TimestampParseError,
  UnsupportedBackendError,
  UnsupportedQueryFeatureError,
  ValidationError,
} from './errors/index.js';

export { normalizeTimestampInput } from './validation/timestamp.js';
export { clonePayloadObject, validateAndNormalizePayload } from './validation/payload.js';
export { compareByLogicalOrder, toPublicRecord } from './records/ordering.js';
export { Datastore } from './datastore/Datastore.js';
export { runQueryWithEngine } from '../queryEngine/runQueryWithEngine.js';
